test:
	nim c -r ./day22.nim <./test.txt

run:
	nim c -r ./day22.nim <./input.txt


test2:
	nim c -r ./day22_p2.nim <./test.txt
	
test2_inf:
	nim c -r ./day22_p2.nim <./test_infinite.txt

run2:
	nim c -r ./day22_p2.nim <./input.txt
