test0:
	nim c -r ./day15.nim 0,3,6 true 10

test1:
	nim c -r ./day15.nim 2,1,3 true 2020

test2:
	nim c -r ./day15.nim 1,2,3 true 2020

test3:
	nim c -r ./day15.nim 2,3,1 true 2020

test4:
	nim c -r ./day15.nim 3,2,1 true 2020

test5:
	nim c -r ./day15.nim 3,1,2 true 2020

run:
	nim c -r ./day15.nim 15,5,1,4,7,0 true 2020

run_p1_using_p2_src:
	nim c -r ./day15_p2.nim 15,5,1,4,7,0 true 2020

run_p2:
	nim c -r ./day15_p2.nim 15,5,1,4,7,0 false 30000000
