test:
	nim c ./day12.nim
	./day12 <./test.txt

run:
	nim c ./day12.nim
	./day12 <./input.txt

test2:
	nim c ./day12_p2.nim
	./day12_p2 <./test.txt

run2:
	nim c ./day12_p2.nim
	./day12_p2 <./input.txt

