test:
	nim c ./day18.nim
	./day18 <./test.txt

run:
	nim c ./day18.nim
	./day18 <./input.txt

test2:
	nim c ./day18_p2.nim
	./day18_p2 <./test.txt

run2:
	nim c ./day18_p2.nim
	./day18_p2 <./input.txt
