test:
	nim c ./day07.nim
	cat ./test.txt  | ./day07

run:
	nim c ./day07.nim
	cat ./input.txt  | ./day07


test2:
	nim c ./day07_p2.nim
	cat ./test.txt  | ./day07_p2

test2_another:
	nim c ./day07_p2.nim
	cat ./another_test.txt  | ./day07_p2


run2:
	nim c ./day07_p2.nim
	cat ./input.txt  | ./day07_p2
