test:
	nim c ./day11.nim
	./day11 <./test.txt

run:
	nim c ./day11.nim
	./day11 <./input.txt


test2:
	nim c ./day11_p2.nim
	./day11_p2 <./test.txt

run2:
	nim c ./day11_p2.nim
	./day11_p2 <./input.txt
