test:
	nim c ./day17.nim
	./day17 < ./test.txt

run:
	nim c ./day17.nim
	./day17 < ./input.txt

test2:
	nim c ./day17_p2.nim
	./day17_p2 < ./test.txt

run2:
	nim c ./day17_p2.nim
	./day17_p2 < ./input.txt
